# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1284, 730)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_2.setStyleSheet("background-color: rgb(46, 49, 54);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 6, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_5.setStyleSheet("background-color: rgb(46, 49, 54);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.Button_Search = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_Search.sizePolicy().hasHeightForWidth())
        self.Button_Search.setSizePolicy(sizePolicy)
        self.Button_Search.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Button_Search.setFont(font)
        self.Button_Search.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Button_Search.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Button_Search.setStyleSheet("QPushButton {\n"
"                background-color: transparent;\n"
"                color: white;\n"
"                border: none;\n"
"                text-decoration: none;\n"
"            }\n"
"\n"
"            QPushButton:hover {\n"
"                color: #00f;\n"
"                text-decoration: underline;\n"
"            }")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icon/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Search.setIcon(icon)
        self.Button_Search.setIconSize(QtCore.QSize(16, 16))
        self.Button_Search.setObjectName("Button_Search")
        self.horizontalLayout_2.addWidget(self.Button_Search)
        self.Button_Create = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_Create.sizePolicy().hasHeightForWidth())
        self.Button_Create.setSizePolicy(sizePolicy)
        self.Button_Create.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Button_Create.setFont(font)
        self.Button_Create.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Button_Create.setMouseTracking(True)
        self.Button_Create.setStatusTip("")
        self.Button_Create.setStyleSheet("QPushButton {\n"
"                background-color: transparent;\n"
"                color: white;\n"
"                border: none;\n"
"                text-decoration: none;\n"
"            }\n"
"\n"
"            QPushButton:hover {\n"
"                color: #00f;\n"
"                text-decoration: underline;\n"
"            }\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Create.setIcon(icon1)
        self.Button_Create.setIconSize(QtCore.QSize(20, 20))
        self.Button_Create.setCheckable(False)
        self.Button_Create.setAutoRepeat(False)
        self.Button_Create.setObjectName("Button_Create")
        self.horizontalLayout_2.addWidget(self.Button_Create)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 6, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_4.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.Button_pageMain = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_pageMain.sizePolicy().hasHeightForWidth())
        self.Button_pageMain.setSizePolicy(sizePolicy)
        self.Button_pageMain.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Button_pageMain.setFont(font)
        self.Button_pageMain.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Button_pageMain.setStyleSheet("QPushButton {\n"
"                background-color: transparent;\n"
"                color: white;\n"
"                border: none;\n"
"                text-decoration: none;\n"
"            }\n"
"\n"
"            QPushButton:hover {\n"
"                color: #00f;\n"
"                text-decoration: underline;\n"
"            }")
        self.Button_pageMain.setObjectName("Button_pageMain")
        self.horizontalLayout.addWidget(self.Button_pageMain)
        self.Button_Report = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_Report.sizePolicy().hasHeightForWidth())
        self.Button_Report.setSizePolicy(sizePolicy)
        self.Button_Report.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Button_Report.setFont(font)
        self.Button_Report.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Button_Report.setStyleSheet("QPushButton {\n"
"                background-color: transparent;\n"
"                color: white;\n"
"                border: none;\n"
"                text-decoration: none;\n"
"            }\n"
"\n"
"            QPushButton:hover {\n"
"                color: #00f;\n"
"                text-decoration: underline;\n"
"            }")
        self.Button_Report.setObjectName("Button_Report")
        self.horizontalLayout.addWidget(self.Button_Report)
        self.Button_Add = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_Add.sizePolicy().hasHeightForWidth())
        self.Button_Add.setSizePolicy(sizePolicy)
        self.Button_Add.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Button_Add.setFont(font)
        self.Button_Add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Button_Add.setStyleSheet("QPushButton {\n"
"                background-color: transparent;\n"
"                color: white;\n"
"                border: none;\n"
"                text-decoration: none;\n"
"            }\n"
"\n"
"            QPushButton:hover {\n"
"                color: #00f;\n"
"                text-decoration: underline;\n"
"            }color: rgb(255, 255, 255);")
        self.Button_Add.setObjectName("Button_Add")
        self.horizontalLayout.addWidget(self.Button_Add)
        self.Button_Setting = QtWidgets.QPushButton(self.frame)
        self.Button_Setting.setMaximumSize(QtCore.QSize(50, 30))
        self.Button_Setting.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Button_Setting.setStyleSheet("\n"
"image: url(:/newPrefix/setting.png);")
        self.Button_Setting.setText("")
        self.Button_Setting.setIconSize(QtCore.QSize(9, 18))
        self.Button_Setting.setObjectName("Button_Setting")
        self.horizontalLayout.addWidget(self.Button_Setting)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setStyleSheet("background-color: rgb(46, 49, 54);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.content_widget = QtWidgets.QWidget()
        self.content_widget.setGeometry(QtCore.QRect(0, 0, 1282, 666))
        self.content_widget.setObjectName("content_widget")
        self.content_layout = QtWidgets.QGridLayout(self.content_widget)
        self.content_layout.setContentsMargins(15, 20, 15, 20)
        self.content_layout.setSpacing(20)
        self.content_layout.setObjectName("content_layout")
        self.scrollArea.setWidget(self.content_widget)
        self.gridLayout.addWidget(self.scrollArea, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_Search.setText(_translate("MainWindow", "Tìm kiếm"))
        self.Button_Create.setText(_translate("MainWindow", "Tạo"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.Button_pageMain.setText(_translate("MainWindow", "TRANG CHỦ"))
        self.Button_Report.setText(_translate("MainWindow", "BÁO CÁO"))
        self.Button_Add.setText(_translate("MainWindow", "THÊM"))
import icon.resource_rc
